### ISSUE TITLE
(intermediate value)(intermediate value)(intermediate value) is not a function since 0.5

### ISSUE THREAD

**Issue by Loreno10** [c3js/c3#2326]
I wanted to do something simple with C3, so I just copied an example form "Getting started" of documentation. Here's my codepen:
https://codepen.io/Loreno/pen/geGvaV?editors=1010

This simple example does not work with C3 versions starting from 0.5.
It works perfectly fine with the previous one: 0.4.22

The exception message that I'm getting is:

> Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not a function
>     at b.m.initParams (c3.min.js:2)
>     at b.m.init (c3.min.js:2)
>     at new w (c3.min.js:2)
>     at Object.S.generate (c3.min.js:2)
>     at pen.js:2

* **C3 version**: 0.5 and 0.5.1
* **D3 version**: 3.5.17
* **Browser**: Chrome 65
* **OS**: Windows 7 x64

**Comment by panthony** [comment]
@Loreno10 Thanks for reporting, the Getting Started needs to be updated.

The latest version of c3js is using D3 V4 and is not compatible anymore with  D3 V3.

**Comment by suhailkc** [comment]
Updating the version on D3 solved my issue.
